### ISSUE TITLE
著者情報の出力位置を変えられるようにしたい

### ISSUE THREAD

**Issue by mypacecreator** [vektor-inc/vk-post-author-display#13]
現状は the_contentフィルターにフックしているので、本文の直後にしか著者情報を出すことができませんが、これだと支障が出るケースがあります。

### 具体的なお困りケース

- wp_link_pages でページ分割している場合に、ページャーが著者情報の下に来る問題
- 同じくthe_contentフィルターを使っているプラグインとのバッティングによる出力順制御できない問題

自動出力をOFFに設定できて、テンプレートに関数記述で出力できるようにするとよいですね。

**Comment by kurudrive** [comment]
デスヨネー
いやー、実はそうなんですよー・・・（・ｗ・；

**Comment by kurudrive** [comment]
※ 別件の不具合と鋭意格闘中で今週末は手が出せません...orz

**Comment by mypacecreator** [comment]
私もプルリク送りたかったんですが年内は手が出せず… とりあえずissueだけ立てた次第です！

**Comment by kurudrive** [comment]
ふぁー、過去に別のスタッフがjsで作った部分が不具合でて、よくわからんから自分で作り直してたりしますー。ふぉー＞ｗ＜
お互いがんばりましょー！

**Comment by kurudrive** [comment]
とりあえず非表示機能はリリースしたのでクローズだん。
