### ISSUE TITLE
VK Post Author Display の 著者情報に載せる投稿タイプにカスタム投稿タイプも対象に

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/vk-post-author-display#14]
view.post-author.php の 108 行目あたりに
```
$loop       = new WP_Query(
	array(
		'post_type'      => 'post',
		'posts_per_page' => 4,
		'author'         => $autorID,
	)
);
```
の記述がありますが、この`'post_type'      => 'post'`の部分にフィルターフックを仕掛けることは可能でしょうか？
関連するスレッドが建っています。
https://vws.vektor-inc.co.jp/forums/topic/vk-post-author-display-%E3%82%92%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E6%8A%95%E7%A8%BF%E3%82%BF%E3%82%A4%E3%83%97%E3%82%82%E5%AF%BE%E8%B1%A1%E3%81%AB

**Comment by kurudrive** [comment]
実装しましたのでcloseしますー。
