### ISSUE TITLE
WP6.0以降でユーザー編集画面で写真が反映されない＆Warning

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vk-post-author-display#55]
@kurudrive 
WP6.0だとユーザープロフィール画面で写真が反映されなかったり、エラー表示をONにしているとPHPのWarningが出ます。
どうも view.admin-profile.php で使ってる global $profileuser  の変数名が6.0で $profile_user になった気配を感じます。

**Comment by kurudrive** [comment]
@mthaichi ありがとうございました。
