### ISSUE TITLE
【お知らせ待ち】【ご要望】最近の投稿の日付部分が、WordPressの日付形式と同じ形式で出力されると嬉しいとのご意見がありました

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-post-author-display#78]
VWSのDiscordよりご意見をいただきましたので、issue化します。

https://discord.com/channels/1086176580675584011/1087240249429741628/1142761453317791825

> お世話になっております。
> 
> VK Post Author Display（https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-post-author-display/ ）の日付部分は
> WordPressの標準機能「日付のフォーマット」と一致せず、Y.m.d形式に限定されるのでしょうか…？
> 
> その他のlightningテーマなどではどの部分も日付のフォーマット通りに出力されておりましたので、
> 統一をご検討いただけると非常にありがたいです！🙏🏻

いったんAssigneesには開発者の皆様をいれさせていただきました。

**Comment by kaorock72** [comment]
お知らせ公開とシェア完了しました！
https://www.vektor-inc.co.jp/product-update/vk-post-author-display-1-23-0/
