### ISSUE TITLE
Double spacing on box

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-post-author-display#84]
https://wordpress.org/support/topic/double-spacing-on-box/

**Comment by WoodleaHome** [comment]
![Screenshot 2024-05-22 at 13 40 05](https://github.com/vektor-inc/vk-post-author-display/assets/162803294/e8df60aa-f37d-47e5-81e5-0019b63997a0)

**Comment by WoodleaHome** [comment]
The gaps are too big (red lines)

**Comment by kurudrive** [comment]
@WoodleaHome 

Normally, it doesn't happen, so it might be due to the theme or other plugins.
Can you paste the specific URL?

**Comment by WoodleaHome** [comment]
I have fixed itDavinOn 23 May 2024, at 18:08, Hidekazu Ishikawa ***@***.***> wrote:﻿
@WoodleaHome
Normally, it doesn't happen, so it might be due to the theme or other plugins.
Can you paste the specific URL?

**Comment by kurudrive** [comment]
> I have fixed it

OK :)
